---
title: "**Data Files Editor**"
output: html_document
---

### **Overview**



```{r,echo=FALSE,results='hide',message=FALSE}
#Load DT, dplyr
library(DT)
#library(dplyr) 
library(here)
library(tidyverse)
library(magrittr)
#library(RCurl)
```

##  Resource table editor
```{r,echo=FALSE,results='hide'}
# Load file for General Table
#generalData <- read_csv(file = here::here("ictr_table_general.csv"))
#generalData
# Load file for Resource Table
resource <- read_csv(file = here::here("data/ictr_table_resources.csv"))

# Create the html version of links in resources
## AwanEdit: added a column "identifier" to the resource table to use it as a merge key variable with the Data provided column entries in other tables
resource_new <- resource %>% 
  mutate(identifier = c("PDX", "HemOnc", "ngchm", "OncoMX", "MethCon5", "CIViC", "BioMuta", "TCIA", "SCGV", "ivyGlimpse", "TCPA", "dcmqi", "Region Templates", "Cistrome", "TOPAS", "TCGA", "1000 Genomes", "TARGET", "CCLE", "dbGAP", "CPTAC", "PheKB", "NSCLC Radiomics", "ICGC"))  %>%  relocate(identifier)

write.csv(resource_new, file = "data/ictr_table_resources_new.csv")
```


```{r,echo=FALSE,results='hide'}
# Load file for General Table
#generalData <- read_csv(file = here::here("ictr_table_general.csv"))
#generalData
```


